### PR TITLE
fixed layers with incorrect legend labels

### LINKED ISSUE #13: Color line data so it doesn't blend with borders
> Transportation- I would recommend that the color of trails be different than muni boundaries so they pop when they are on. Especially since many rail trails follow creeks which are frequently the boundaries between munis too. There is a bike lane around North park that is not on the map. “Bike Lane” and “On Street Route” seem to be the same color. I there a difference in the field like a dedicated lane vs just a bike logo painted on the street?  The City steps layer is amazing!

### PR DESCRIPTION
**Pull request by saylorsd**
changed color of bike trails layer for better visibility
fixes #13

### CODE REVIEW

**Comment by saylorsd** [comment]
@AlyFear I published these changes to the [staging site]( https://tools.wprdc.org/green-test).

Please take a look when you have a chance.

**Comment by AlyFear** [comment]
Steve,
Can you list the numbers so I know which ones to check?  Because #14 doesn’t show a change for me yet.  I don’t want to look for the wrong ones.

Alyson Fearon
Community Conservation Director
Allegheny Land Trust

416 Thorn Street  |  Sewickley, PA  |  15143
Office: 412.741.2750x204  |  Mobile: 314.556.4892

www.alleghenylandtrust.org<http://www.alleghenylandtrust.org/>
facebook<https://www.facebook.com/alleghenylandtrust> | flickr<https://www.flickr.com/photos/68211232@N02/albums> | instagram<https://instagram.com/alleghenylandtr/>
linkedin<http://www.linkedin.com/company/allegheny-land-trust> | pinterest<https://www.pinterest.com/AlleghenyLandTr/> | twitter<https://twitter.com/AlleghenyLandTr> | youtube<https://www.youtube.com/user/AlleghenyLandTrust/videos>
[ALTlogo_esig_small][accreditationseal_small]

**Comment by AlyFear** [comment]
Almost there
trails
So the legend is perfect, but we are no longer using obnoxious purple as the layer legend on the left.

**Comment by saylorsd** [comment]
Should I just tone the purple down, or switch to a new color?

**Comment by AlyFear** [comment]
Oh, the purple for the Bike Trails in the menu now doesn’t match any of the actual colors you applied when you split it out in the legend.  Any of those legend colors would work just fine!

Alyson Fearon
Community Conservation Director
Allegheny Land Trust

416 Thorn Street  |  Sewickley, PA  |  15143
Office: 412.741.2750x204  |  Mobile: 314.556.4892

www.alleghenylandtrust.org<http://www.alleghenylandtrust.org/>
facebook<https://www.facebook.com/alleghenylandtrust> | flickr<https://www.flickr.com/photos/68211232@N02/albums> | instagram<https://instagram.com/alleghenylandtr/>
linkedin<http://www.linkedin.com/company/allegheny-land-trust> | pinterest<https://www.pinterest.com/AlleghenyLandTr/> | twitter<https://twitter.com/AlleghenyLandTr> | youtube<https://www.youtube.com/user/AlleghenyLandTrust/videos>
[ALTlogo_esig_small][accreditationseal_small]

**Comment by saylorsd** [comment]
Ahhh. gotcha.  It's up on http://tools.wprdc.org/green-test/

**Pull request merged**
